set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_OPENCV -std=c++0x")
set(HAS_NEON FALSE)
execute_process(COMMAND uname -m COMMAND tr -d '\n' OUTPUT_VARIABLE ARCH)
if (ARCH MATCHES "^(arm)")
  set(HAS_NEON TRUE)
  add_definitions(-mfpu=neon)
else()
  add_definitions(-mssse3)
endif()
